config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  get 'home' => 'static_pages#home'
  get 'about' => 'static_pages#about'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'signup' => 'users#new'
  resources :users

  resources :notifications, only: :show
  delete 'notifications' => 'notifications#destroy'

  get 'notifications' => 'notifications#index'

  get 'games/new/custom' => 'games#custom'
  resources :games, except: :edit do
    resources :guesses
  end

end

app/models/notifications/completed_game_notification.rb
class CompletedGameNotification < Notification
  belongs_to :game, foreign_key: "game_id"

  def description
    "#{sender.name} #{win_status} your game!"
  end

  def read_action
    game
  end

  private

  def win_status
    game.won? ? "won" : "lost"
  end
end

app/models/notifications/new_game_notification.rb
class NewGameNotification < Notification
  belongs_to :game, foreign_key: "game_id"

  def description
    "#{sender.name} sent you a new game!"
  end

  def read_action
    game
  end
end

app/models/notifications/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :sender, foreign_key: "sender_id", class_name: "User"
  belongs_to :receiver, foreign_key: "receiver_id", class_name: "User"

  def read_action
    :back
  end

  def mark_read
    update(read: true)
  end

  def mark_unread
    update(read: false)
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :find_notification, only: :show

  def index
    @notifications = FetchRecentNotifications.new(User.find(params[:user_id])).call
    @unread_notifications = @notifications.reject(&:read?).length
  end

  def show
    @notification.read = true
    @notification.save!
    redirect_to @notification.read_action
  end

  def destroy
    ClearNotifications.new(current_user).call
    render nothing: true
  end

  private

  def find_notification
    @notification = Notification.find(params[:id])
  end

  def guess_params
    params.require(:notification).permit(:sender_id, :receiver_id, :game_id)
  end
end

app/views/notifications/_notification.html.erb
<li class="notification<%= ' unread' if !notification.read? %>" data-id="<%= notification.id %>">
  <%= link_to notification.description, notification_path(notification) %>
</li>

app/views/notifications/_notification_bottom.html.erb
<li class="divider"></li>

<li class="clear-notifications">
  <%= link_to "Clear All", notifications_path, method: :delete, remote: true %>
</li>

app/views/notifications/index.js.erb
$('.notification').remove();

if (<%= @notifications.length == 0 %>) {
  $("#notifications").prepend("<li class='notification'><a href='#'>No Notifications</a></li>");
} else {
  $('#notifications').prepend("<%=raw escape_javascript(render(@notifications)) %>");
}

$("#notifications-toggle").removeClass("unread");
if (<%= @unread_notifications > 0 %>) {
  $("#notifications-toggle").addClass("unread");
}