config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  get 'home' => 'static_pages#home'
  get 'about' => 'static_pages#about'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'signup' => 'users#new'
  resources :users

  resources :notifications, only: :show
  delete 'notifications' => 'notifications#destroy'

  get 'notifications' => 'notifications#index'

  get 'games/new/custom' => 'games#custom'
  resources :games, except: :edit do
    resources :guesses
  end

end

app/views/layouts/_errors.html.erb
<% if item.errors.any? %>
  <div id="error_explanation">
    <h2>There <%= item.errors.count == 1 ? 'was an error' : 'were ' + pluralize(item.errors.count, "error") %> stopping the <%= item.class.name.downcase %> from being made:</h2>
    <ul>
    <% item.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% unless flash.empty? %>
  <script type="text/javascript">
    toastr.options = {
      "closeButton": true,
      "positionClass": "toast-bottom-right",
      "progressBar": true,
      "onclick": function() {
        $(".notification.unread:eq(" + index + ")").find("a")[0].click();
      }
    }
    <% flash.each do |message_type, message| %>
    <% type = message_type.to_s.gsub('alert', 'error').gsub('notice', 'info').gsub('danger', 'error') %>
      toastr['<%= type %>']('<%= message %>');
    <% end %>
  </script>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://github.com/NoodleChump/devtrain-rails-hangman">Rails Hangman</a>
    by <a href="http://github.com/NoodleChump">Jordane Lew</a>
  </small>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">

    <nav class="">

      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Rails Hangman", root_path, id: "logo" %>
      </div>

      <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   home_path %></li>
        <li><%= link_to "Games",  games_path %></li>
        <li><%= link_to "Players",  users_path %></li>
        <li><%= link_to "About",   about_path %></li>

        <!-- Notifications -->
        <% notifications = FetchRecentNotifications.new(current_user).call %>
        <li id="notifications-dropdown" class="dropdown">
          <a href="#" id="notifications-toggle" class="dropdown-toggle<%= ' unread' if notifications.reject(&:read?).length > 0 %>" data-toggle="dropdown">
            Notifications
          <b class="caret"></b></a>
          <ul id="notifications" class="dropdown-menu">

            <% if notifications.size == 0 %>
              <li class='notification'><a href='#'>No Notifications</a></li>
            <% else %>
              <%= render(notifications) %>
            <% end %>

            <li class="divider"></li>
            <li class="clear-notifications">
              <%= link_to "Clear All", notifications_path, method: :delete, remote: true %>
            </li>
          </ul>
        </li>

        <% if logged_in? %>
          <!-- Profile -->
          <li id="user-dropdown" data-id="<%= current_user.id %>" class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= current_user.name %>
            <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log Out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>

          <!-- New Game -->
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              New Game
            <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Ranked Game", new_game_path %></li>
              <li><%= link_to "Custom Game", games_new_custom_path %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Register", signup_path %></li>
          <li><%= link_to "Log In",   login_path %></li>
        <% end %>
      </ul>
    </div>
    </nav>
  </div>
</header>

app/views/layouts/_new_game_buttons.html.erb
<%= button_to 'New Ranked Game', new_game_path, { class: "btn btn-primary", method: :get } %>
<br />
<%= button_to 'New Custom Game', games_new_custom_path, { class: "btn btn-secondary", method: :get } %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= "[DEV] " if Rails.env.development? %><%= yield(:title) + " | " if yield(:title).present? %> Rails Hangman</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag    '//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css', media: 'all' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js" %>
    <%= csrf_meta_tags %>

    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>

    <div class="container">
      <%= render 'layouts/flash_messages' %>
      <%= yield %>
      <%= render 'layouts/footer' %>

      <%= debug(params) if Rails.env.development? %>
    </div>

  </body>

  <%= javascript_include_tag "games_form" %>
  <%= javascript_include_tag "guesses_form" %>
  <%= javascript_include_tag "players_form" %>
  <%= javascript_include_tag "spectation" %>
</html>